apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nlw-passin
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/Natanaelvich/devops-concepts_nlw-rocketseat-24.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: nlw-helm
  syncPolicy:
    automated:
      prune: true