name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and push'
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=${SHA}" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: natanaelvich/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}, natanaelvich/nlw.service.passin:latest

    - name: Update image tag
      uses: fjogeleit/yaml-update-action@main
      with:
        branch: main
        valueFile: 'deploy/values.yaml'
        propertyPath: 'image.tag'
        value: "${{ steps.generate_sha.outputs.sha }}"
        commitChange: true
        message: 'NEW: Update tag in values helm'